---
version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: catalogo
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
      
  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass local
    volumes: 
      - ./cache:/data
